CREATE TABLE ROLES (
    ROLE_ID INT PRIMARY KEY AUTO_INCREMENT,
    ROLE_NAME VARCHAR(20) NOT NULL UNIQUE
);

INSERT INTO
    ROLES (ROLE_NAME)
VALUES ('ADMIN'),
    ('PRACOWNIK'),
    ('SEKRETARZ');

CREATE TABLE USERS (
    LOGIN VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(255) NOT NULL,
    IMIE VARCHAR(50) NOT NULL,
    NAZWISKO VARCHAR(50) NOT NULL,
    ROLE_ID INT NOT NULL,
    STATUS VARCHAR(50) DEFAULT 'not-available',
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ROLE_ID)
);

CREATE TABLE WORK_SESSIONS (
    ID_SESSION INT PRIMARY KEY AUTO_INCREMENT,
    LOGIN VARCHAR(50) NOT NULL,
    START_TIME DATETIME NOT NULL,
    END_TIME DATETIME DEFAULT NULL,
    FOREIGN KEY (LOGIN) REFERENCES USERS (LOGIN)
);

CREATE TABLE CHAT (
    ID_CHAT INT PRIMARY KEY AUTO_INCREMENT,
    CHAT_NAME VARCHAR(100) DEFAULT NULL,
    IS_GROUP BOOLEAN DEFAULT FALSE
);

CREATE TABLE CHAT_MEMBERS (
    ID_CHAT INT NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_CHAT, LOGIN),
    FOREIGN KEY (ID_CHAT) REFERENCES CHAT (ID_CHAT) ON DELETE CASCADE,
    FOREIGN KEY (LOGIN) REFERENCES USERS (LOGIN) ON DELETE CASCADE
);

CREATE TABLE MESSAGES (
    ID_MESSAGE INT PRIMARY KEY AUTO_INCREMENT,
    ID_CHAT INT NOT NULL,
    SENDER_LOGIN VARCHAR(50) NOT NULL,
    CONTENT TEXT NOT NULL,
    SENT_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    IS_URGENT BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_CHAT) REFERENCES CHAT (ID_CHAT) ON DELETE CASCADE,
    FOREIGN KEY (SENDER_LOGIN) REFERENCES USERS (LOGIN)
);